# Server Configuration
server:
  port: 8080

# Application Configuration
spring:
  application:
    name: blog-backend

  # Database Configuration
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  # Hibernate (JPA) Configuration
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

# Logging Configuration
logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
      hibernate: DEBUG

# Spring Actuator (Health Monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    status:
      http-mapping:
        UP: 200
        DOWN: 503
        UNKNOWN: 404

# Swagger API Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

# Frontend Configuration
frontend:
  url: ${FRONTEND_URL}
